/*
 * app.cpp - Start-up order, main loop and shutdown sequence of the Muki Watch firmware.
 *
 *   src/core       system services (I2C lock, memory, UI wake-up), settings, formatting
 *   src/drivers    display + touch, PMU, motion sensor, audio, RTC, SD card
 *   src/services   clock, Wi-Fi, Bluetooth, phone link, weather, notifications, activity,
 *                  sleep, alarms, countdown, workouts, calendar, OTA, WLED, car link, ...
 *   src/ui         widget kit, system screens (navigation, launcher, quick panel, AOD,
 *                  notifications), watch faces, apps
 *   src/assets     fonts, icons and images (generated by tools/)
 *
 * LVGL runs in this (the Arduino loop) task only; background tasks publish state and wake
 * the loop, which applies it.
 */
#include "app.h"

#include <Arduino.h>
#include "core/settings.h"
#include "core/system.h"
#include "drivers/audio.h"
#include "drivers/display.h"
#include "drivers/imu.h"
#include "drivers/power.h"
#include "drivers/sd_card.h"
#include "services/activity.h"
#include "services/agenda.h"
#include "services/alarms.h"
#include "services/battery_saver.h"
#include "services/bluetooth.h"
#include "services/car_link.h"
#include "services/clap_control.h"
#include "services/clock.h"
#include "services/countdown.h"
#include "services/net_worker.h"
#include "services/notifications.h"
#include "services/ota.h"
#include "services/phone.h"
#include "services/sleep_tracker.h"
#include "services/weather.h"
#include "services/wifi.h"
#include "services/wled.h"
#include "services/workout.h"
#include "ui/apps/apps.h"
#include "ui/kit/kit.h"
#include "ui/system/nav.h"
#include "ui/system/notification_center.h"
#include "ui/system/screen.h"
#include "ui/system/system_ui.h"

#define APP_MAX_WAIT_MS 50  // the loop runs at least this often

// Before a restart or power off: store what is pending, then the screen goes dark.
static void app_shutdown(bool restart) {
  Serial.println(restart ? "[APP] restart" : "[APP] power off");
  settings_flush();
  activity_save();
  agenda_flush();
  screen_power_off();
  if (!restart) power_shutdown();
}

void app_init() {
  system_init();
  system_set_shutdown_handler(app_shutdown);

  power_init();         // the PMU feeds every other peripheral: first
  display_init();       // lv_init(), panel, touch, draw buffers (sized to the free internal RAM)
  settings_init();      // NVS -> subjects (needs lv_init)
  kit_init();
  sd_init();            // optional: the watch works without a card
  audio_init();

  clock_init();         // RTC -> system time, before anything that looks at the date
  net_worker_init();
  notify_init();
  agenda_init();
  weather_init();       // cached forecast, before the faces show it
  imu_init();
  activity_init();
  sleep_tracker_init();
  alarms_init();
  countdown_init();
  workout_init();
  battery_saver_init();
  wled_init();
  clap_control_init();
  car_link_init();

  system_ui_init();
  notification_center_init();
  alarm_app_init();
  timer_app_init();
  nav_init();           // tiles and the chosen watch face
  screen_init();
  power_start(system_ui_on_power);
  phone_set_event_handler(system_ui_on_phone);

  wifi_init();          // the radios start last: they take the most internal RAM
  bt_init();
  phone_init();
  ota_init();
  mem_log("Boot done");
}

// Runs LVGL, then sleeps until the next LVGL timer is due or something wakes the loop
// (touch, wrist raise, network results): the CPU idles instead of spinning.
void app_loop() {
  screen_service();
  uint32_t next_ms = lv_timer_handler();
  if (next_ms == LV_NO_TIMER_READY || next_ms > APP_MAX_WAIT_MS) next_ms = APP_MAX_WAIT_MS;
  system_ui_wait(next_ms);
}
