/*
 * images.h - Bitmaps of the watch UI. Generated by tools/gen_images.py: do not edit.
 *
 *   img_face_bg   368x397 RGB565 background of the watch faces and tiles
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_IMAGE_DECLARE(img_face_bg);

#ifdef __cplusplus
}
#endif
