/*
 * fonts.h - Fonts of the watch UI. Generated by tools/gen_fonts.py: do not edit.
 *
 *   font_text_20/24/28/32   Montserrat Medium: Latin-1, Latin Extended-A (Turkish), Cyrillic
 *   font_bold_28            Montserrat Bold ASCII and the degree sign (watch face labels)
 *   font_num_44/64/110      Montserrat Light digits and : . , / % ° + - (clocks, timers);
 *                           other characters fall back to font_text_32
 *   font_light_180          Montserrat Light digits, ':' and '-' (hours of the Digital face)
 *   font_icons_24/32/48     Font Awesome 5 Free icons (icons.h); they fall back to the
 *                           built-in Montserrat, so LV_SYMBOL_* and plain text work too
 *   font_icons_96           large weather glyphs (SUN, MOON, CLOUD_SUN, CLOUD_MOON, CLOUD, CLOUD_RAIN, CLOUD_SHOWERS, SNOWFLAKE, BOLT, SMOG)
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(font_text_20)
LV_FONT_DECLARE(font_text_24)
LV_FONT_DECLARE(font_text_28)
LV_FONT_DECLARE(font_text_32)
LV_FONT_DECLARE(font_bold_28)
LV_FONT_DECLARE(font_num_44)
LV_FONT_DECLARE(font_num_64)
LV_FONT_DECLARE(font_num_110)
LV_FONT_DECLARE(font_light_180)
LV_FONT_DECLARE(font_icons_24)
LV_FONT_DECLARE(font_icons_32)
LV_FONT_DECLARE(font_icons_48)
LV_FONT_DECLARE(font_icons_96)

#ifdef __cplusplus
}
#endif
