"""
gen_images.py - Converts the bitmaps of the watch UI (tools/assets) into LVGL 9 C images in
Smartwatch/src/assets/images, plus images.h.

  python tools/gen_images.py

RGB565 with ordered (Bayer) dithering, which keeps dark gradients free of banding. Needs
Pillow (pip install pillow).
"""
import os

from PIL import Image

TOOLS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS)
ASSETS = os.path.join(TOOLS, "assets")
OUT = os.path.join(REPO, "Smartwatch", "src", "assets", "images")
SCREEN_W = 368
BAYER = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]


def to_rgb565(im):
    w, h = im.size
    px = im.load()
    out = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y][:3]
            t = (BAYER[y % 4][x % 4] + 0.5) / 16.0
            r5 = min(31, int(r * 31 / 255 + t))
            g6 = min(63, int(g * 63 / 255 + t))
            b5 = min(31, int(b * 31 / 255 + t))
            v = (r5 << 11) | (g6 << 5) | b5
            out += bytes((v & 0xFF, v >> 8))
    return out


def write_image(name, im, what, summary, source):
    data = to_rgb565(im)
    w, h = im.size
    lines = [
        "/*",
        f" * {name}.c - {what}",
        f" * {w}x{h} RGB565, ordered dithering. Generated by tools/gen_images.py from",
        f" * tools/assets/{source}: do not edit.",
        " */",
        '#include "lvgl.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "#ifndef LV_ATTRIBUTE_LARGE_CONST",
        "#define LV_ATTRIBUTE_LARGE_CONST",
        "#endif",
        "",
        f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{",
    ]
    for i in range(0, len(data), 24):
        lines.append("  " + ",".join(f"0x{b:02X}" for b in data[i:i + 24]) + ",")
    lines += [
        "};",
        "",
        f"const lv_image_dsc_t {name} = {{",
        "  .header = {",
        "    .magic = LV_IMAGE_HEADER_MAGIC,",
        "    .cf = LV_COLOR_FORMAT_RGB565,",
        "    .flags = 0,",
        f"    .w = {w},",
        f"    .h = {h},",
        f"    .stride = {w * 2},",
        "  },",
        f"  .data_size = sizeof({name}_map),",
        f"  .data = {name}_map,",
        "};",
        "",
    ]
    path = os.path.join(OUT, name + ".c")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"  {name}.c  {w}x{h}  {len(data) // 1024} kB of pixels")
    return f"{name:<13} {w}x{h} RGB565 {summary}"


def main():
    print("Images ->", os.path.relpath(OUT, REPO))
    listing = []
    bg = Image.open(os.path.join(ASSETS, "bg.png")).convert("RGB")
    left = (bg.size[0] - SCREEN_W) // 2
    bg = bg.crop((left, 0, left + SCREEN_W, bg.size[1]))
    listing.append(("img_face_bg", write_image(
        "img_face_bg", bg, "Background of the watch faces and tiles: dark geometric tiles, round vignette.",
        "background of the watch faces and tiles", "bg.png")))

    header = [
        "/*",
        " * images.h - Bitmaps of the watch UI. Generated by tools/gen_images.py: do not edit.",
        " *",
    ] + [f" *   {text}" for _, text in listing] + [
        " */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ] + [f"LV_IMAGE_DECLARE({name});" for name, _ in listing] + [
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    open(os.path.join(OUT, "images.h"), "w", encoding="utf-8", newline="\n").write("\n".join(header))


if __name__ == "__main__":
    main()
